### PR TITLE
Playback fix

### PR DESCRIPTION
**Pull request by Gujal00**
1. Add token fetch during playback
2. There was a mix of tabs and spaces being used for indenting. Replaced all tabs with four spaces as per Kodi Developer guidelines

### CODE REVIEW

**Comment by dbkalyan** [comment]
Still not fixed. Keep getting errors.

**Comment by mar1a** [comment]
It worked for me after commenting the following lines.
#from addon.common.addon import Addon
#addon = Addon(addon_id, sys.argv)
Kodi-17.6, libreelec-8.2.1

**Comment by Gujal00** [comment]
@marla
Those changes were part of 1.15 release which is not here in Github unfortunately.

**Comment by rubanrex** [comment]
@gujal how to get that working version?

**Comment by Gujal00** [comment]
@rubanrex 
Look in the support thread 
https://forum.kodi.tv/showthread.php?tid=241506&pid=2682930#pid2682930

**Comment by rubanrex** [comment]
@Gujal00  thank you, this version is working great

**Comment by dbkalyan** [comment]
@YoColdRain . Thanks. Working perfectly.

**Comment by dbkalyan** [comment]
@Gujal00.  Do you know whether Hotstar has upgraded their version which is making the addon not to work? Keeps saying that "you are using old version of Hotstar. Please upgrade". I see @YoColdRain is also silent on this issue. Your contribution would be appreciated.  I am aware Kodi has changed to Python 2.25 whereas old addon was on 2.17 version. Changing the .xml file did not work.

**Pull request merged**
